name: "Install Ubuntu packages"

description: "Installs the necessary Ubuntu packages"

branding.icon: download

inputs:
  with_ninja:
    description: If set, adds the ninja packages
    required: false
    default: ${{ true }}
  with_clang:
    description: If set, adds the clang packages
    required: false
    default: ${{ false }}
  with_llvm_linker:
    description: If set, adds the llvm packages
    required: false
    default: ${{ true }}
  with_doxygen:
    description: If set to, adds the doxygen packages
    required: false
    default: ${{ false }}
  with_lcov:
    description: If set, adds the packages for code coverage analysis
    required: false
    default: ${{ false }}
    
runs:
  using: "composite"
  steps:
    - name: Add the fundamentals
      env: 
        package-list: 'g++ cmake clang-tidy cmake cppcheck iwyu libboost-all-dev librange-v3-dev libeigen3-dev '
    - name: Add ninja
        if: inputs.with_ninja
        env:
          package-list: ${{ package-list }}:${{ 'ninja-build ' }}
    - name: Add clang
      if: inputs.with_clang
      env:
        package-list: ${{ package-list }}:${{ 'clang ' }}
    - name: Add llvm
      if: inputs.with_llvm_linker
      env: 
        package-list: ${{ package-list }}:${{ 'lld ' }}
    - name: Add doxygen
      if: inputs.with_doxygen
      env:
        package-list: ${{ package-list }}:${{ 'doxygen graphviz gsfonts biber ' }}
    - name: Add lcov
      if: inputs.with_lcov
      env:
        package-list: ${{ package-list }}:${{ 'lcov ' }
    - name: Install
      run: |
        sudo apt update
        sudo apt install ${{ package-list }}
