name: "Install Ubuntu packages"

description: "Installs the necessary Ubuntu packages"

branding.icon: download

inputs:
  with_ninja:
    description: If set, adds the ninja packages
    required: false
    default: true
  with_clang:
    description: If set, adds the clang packages
    required: false
    default: false
  with_llvm_linker:
    description: If set, adds the llvm packages
    required: false
    default: true
  with_doxygen:
    description: If set to, adds the doxygen packages
    required: false
    default: false
  with_lcov:
    description: If set, adds the packages for code coverage analysis
    required: false
    default: false
    
runs:
  using: "composite"
  steps:
    - name: Add the fundamentals
      run: echo "PACKAGE_LIST=g++ cmake clang-tidy cppcheck iwyu libboost-all-dev librange-v3-dev libeigen3-dev " >> $GITHUB_ENV
      shell: bash
    - name: Add ninja
      if: inputs.with_ninja == true
      run: echo "PACKAGE_LIST=${{ format('{0} {1} ',env.PACKAGE_LIST, 'ninja-build') }}" >> $GITHUB_ENV
      shell: bash
    - name: Add clang
      if: inputs.with_clang == true
      run: echo "PACKAGE_LIST=${{ format('{0} {1} ',env.PACKAGE_LIST, 'clang') }}" >> $GITHUB_ENV
      shell: bash
    - name: Add llvm
      if: inputs.with_llvm_linker == true
      run: echo "PACKAGE_LIST=${{ format('{0} {1} ',env.PACKAGE_LIST, 'lld') }}" >> $GITHUB_ENV
      shell: bash
    - name: Add doxygen
      if: inputs.with_doxygen == true
      run: echo "PACKAGE_LIST=${{ format('{0} {1} ',env.PACKAGE_LIST, 'doxygen graphviz gsfonts biber') }}" >> $GITHUB_ENV
      shell: bash
    - name: Add lcov
      if: inputs.with_lcov == true
      run: echo "PACKAGE_LIST=${{ format('{0} {1} ',env.PACKAGE_LIST, 'lcov') }}" >> $GITHUB_ENV
      shell: bash
   # - name: Install
   #   run: |
   #     sudo apt-get update
   #     sudo apt-get install ${{ env.PACKAGE_LIST }}  --no-install-recommends
   #   shell: bash

