# Configures code coverage

if(NOT DEFINED ENABLE_CODE_COVERAGE)
	message(FATAL_ERROR "ENABLE_CODE_COVERAGE not defined")
endif()

set(COVERAGE_TARGET CoverageTarget)
herd_add_interface_library(TARGET ${COVERAGE_TARGET} INSTALL)

if(ENABLE_CODE_COVERAGE)
	if(COMPILER_CXX_COVERAGE_FLAGS AND LINKER_CXX_COVERAGE_FLAGS)
	  target_compile_options(${COVERAGE_TARGET} INTERFACE ${COMPILER_CXX_COVERAGE_FLAGS})
	  target_link_options(${COVERAGE_TARGET} INTERFACE ${LINKER_CXX_COVERAGE_FLAGS})
	else()
		message(FATAL_ERROR "COMPILER_CXX_COVERAGE_FLAGS and/or LINKER_CXX_COVERAGE_FLAGS not defined")  
	endif()
endif()