name: Nightly

on:
  # Triggers at 22:14 every day
  schedule:
    - cron:  '14 22 * * *'

  # Manual trigger
  workflow_dispatch:  

env:
  BUILD_TYPE: Debug
  BUILD_SYSTEM_ARG: ''
  
jobs:
  nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: ['g++', 'clang']
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set environment
      run: |
        echo "WITH_NINJA=${{ matrix.compiler == 'g++' }}" >> $GITHUB_ENV
        echo "WITH_CLANG=${{ matrix.compiler == 'g++' }}" >> $GITHUB_ENV
    
    - uses: ./.github/actions/install-ubuntu-packages
      with:
        with_ninja: env.WITH_NINJA
        with_clang: env.WITH_CLANG
        with_llvm_linker: ${{ true }}
        with_doxygen: ${{ false }}
        with_lcov: ${{ false }}
        
    - name: Set build system
      if: env.WITH_NINJA
      run: echo "env.BUILD_SYSTEM_ARG=-G Ninja" >> $GITHUB_ENV
      
    - name: Build
      run: |
        cmake ${{ env.BUILD_SYSYEM_ARG }} -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D USE_SANITISER=ON -D CMAKE_CXX_COMPILER=${{ matrix.compiler }}
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run the unit tests
      working-directory: ${{github.workspace}}/build
      run: |
        cmake ${{github.workspace}} -D UNIT_TEST_LEVEL=2_Nightly
        ctest -C ${{env.BUILD_TYPE}} -VV
