name: Nightly

on:
  # Triggers at 22:00 every day
  schedule:
    - cron:  '00 22 * * *'

  # Manual trigger
  workflow_dispatch:  

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      # CMake needs doxygen to build the docs target
      # 20.04 uses g++ 9.3 and clang-tidy-10 by default
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install g++-11 llvm-12-tools
        sudo apt install libboost-dev libboost-all-dev librange-v3-dev libeigen3-dev -DCMAKE_CXX_COMPILER=g++-11 -DCLANG-TIDY-NAME=clang-tidy-12
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        cmake .. -DUNIT_TEST_LEVEL=2_Nightly
        ctest -C ${{env.BUILD_TYPE}} -VV
