name: Nightly

on:
  # Nightly trigger
  schedule:
    - cron:  '41 12 * * *'

  # Manual trigger
  workflow_dispatch:  

env:
  BUILD_TYPE: Debug
  
jobs:
  nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: ['g++', 'clang++']
        
    steps:
    - uses: actions/checkout@v3
    
    - uses: ./.github/actions/install-ubuntu-packages
      with:
        with_ninja: ${{ true }}
        with_clang: ${{ matrix.compiler == 'clang++' }}
        with_llvm_linker: ${{ true }}
        with_doxygen: ${{ false }}
        with_lcov: ${{ false }}
      
    - name: Build
      run: |
        cmake -G Ninja -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D USE_SANITISER=ON -D CMAKE_CXX_COMPILER=${{ matrix.compiler }}
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run the unit tests
      working-directory: ${{github.workspace}}/build
      run: |
        cmake ${{github.workspace}} -D UNIT_TEST_LEVEL=2_Nightly
        ctest -C ${{env.BUILD_TYPE}} -VV
