name: Nightly

on:
  # Triggers at 22:00 every day
  schedule:
    - cron:  '00 22 * * *'

  # Manual trigger
  workflow_dispatch:  

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      # CMake needs doxygen to build the docs target
      run: >
        sudo apt-get update
        sudo apt-get install g++-11 clang ninja-build
                             libboost-all-dev librange-v3-dev libeigen3-dev 
                             clang-tidy cmake cppcheck iwyu
    
    - name: Build with g++
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_SANITISER=ON -DCMAKE_CXX_COMPILER=g++
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j2

    - name: Test the g++ build
      working-directory: ${{github.workspace}}/build
      run: |
        cmake ${{github.workspace}} -DUNIT_TEST_LEVEL=2_Nightly
        ctest -C ${{env.BUILD_TYPE}} -VV

    - name: Build with clang
      run: |
        cmake -B ${{github.workspace}}/clang/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_SANITISER=ON -DCMAKE_CXX_COMPILER=clang++
        cmake --build ${{github.workspace}}/clang/build --config ${{env.BUILD_TYPE}} -j2

    - name: Test the clang build
      working-directory: ${{github.workspace}}/clang/build
      run: |
        cmake ${{github.workspace}} -DUNIT_TEST_LEVEL=2_Nightly
        ctest -C ${{env.BUILD_TYPE}} -VV    

