name: Nightly

on:
  # Triggers at 22:14 every day
  schedule:
    - cron:  '14 22 * * *'

  # Manual trigger
  workflow_dispatch:  

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: ./.github/actions/install-ubuntu-packages@main
      with:
        with_ninja: ${{ true }}
        with_clang: ${{ true }}
        with_llvm_linker: ${{ true }}
        with_doxygen: ${{ false }}
        with_lcov: ${{ false }}
        
    - name: Build with g++
      run: |
        cmake -G Ninja -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D USE_SANITISER=ON -D CMAKE_CXX_COMPILER=g++
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run the unit tests (g++)
      working-directory: ${{github.workspace}}/build
      run: |
        cmake ${{github.workspace}} -D UNIT_TEST_LEVEL=2_Nightly
        ctest -C ${{env.BUILD_TYPE}} -VV

    - name: Build with clang
      # Uses the platform default as the build system 
      run: |
        cmake -B ${{github.workspace}}/clang/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D USE_SANITISER=ON -D CMAKE_CXX_COMPILER=clang++
        cmake --build ${{github.workspace}}/clang/build --config ${{env.BUILD_TYPE}} -j2

    - name: Run the unit tests (clang)
      working-directory: ${{github.workspace}}/clang/build
      run: |
        cmake ${{github.workspace}} -D UNIT_TEST_LEVEL=2_Nightly
        ctest -C ${{env.BUILD_TYPE}} -VV    

