name: TestAction

on:
  # Manual trigger
  workflow_dispatch:  

jobs:
  test-action:
    runs-on: ubuntu-latest
    
    env:
      WITH_CLANG: ${{ true }}
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: ./.github/actions/install-ubuntu-packages
      with:
        with_ninja: true
        with_clang: env.WITH_CLANG
        with_llvm_linker: true
        with_doxygen: false
        with_lcov: false
